%%

load '/groups/saalfeld/home/bogovicj/tmp/dawmr_debug.mat'
% load '/groups/saalfeld/home/bogovicj/tmp/dawmr_debug2.mat'

% winSz = size(data);
% centSz = size( this.dc_p.centroids );


%%
% % newcents = eye( 120, 125 ) + 0.01.*randn(120,125);
% % newcents = eye( 120, 125 ) + 0.01.*randn(120,125);
% 
% newcents = zeros([ 2 centSz(2)], 'single');
% newcents(1,1) = 0.3;
% newcents(2,2) = 0.9;
% 
% % newcents = 10 + randn( 2, 125);
% % newcents = rand( 5, 125);
% % 
% % data = reshape( this.dc_p.centroids(1,:), [5 5 5]) + 0.001 .* rand(5,5,5);
% % data = reshape( newcents(2,:), ...
% %         [5 5 5]);
%     
% % data = 0.01.*randn(5,5,5);
% % data = rand(5,5,5);
% 
% % data = zeros(5,5,5);
% % data(1,1,1) = 0.3
% data = -reshape( newcents(2,:), winSz);
% 
% centroids_stack = {newcents};
% num_clusters_stack = size(newcents,1);


%%

r=[1 1 2];

old_cents = centroids_stack{1};

n_clusters = 5;
dim_clusters = size( old_cents, 1 );

for i = 1:n_clusters
    
    cents_rs = reshape( old_cents(i,:), [ 5 5 5 ]);
    cents_rs_sm = resampleRatioCenter( cents_rs, r );
    
    if( i == 1 )
        dim_clusters_sub = numel( cents_rs_sm );
        newcents_sub = zeros( n_clusters, dim_clusters_sub, 'single' );
    end
    
    newcents_sub(i,:) = cents_rs_sm(:)';
  
end


centroids_stack_sub = { newcents_sub };
centroids_stack_new = { old_cents(1:n_clusters,:) };

% data_sub = single( resampleRatioCenter( data, r ));

pooling_offsets_stack = {[0 0 0]};
kmeans_type_stack = 3;

patch_dim_stack_sub = size( cents_rs_sm );
z_sub = ((patch_dim_stack_sub(3) - 1) / 2 ) + 1;

%%

% rng = 0 : (1/4) : 1;
% [~,~,zvol] = meshgrid( rng, rng, rng ); 
% % zvol = zvol + 0.01.*rand( size(zvol));
% data = single(zvol);
% % data_sub = single(zvol(:,:,1:2:end));

data     = 0.2.*ones(5,5,5, 'single');
% data_sub = 0.2.*ones(5,5,3, 'single');


data_sub = single( resampleRatioCenter( data, r ));

%%

clear mex;
% feats = dawmr_compute_features_mex( ...
feats = dawmr_compute_features_debug_mex( ...
                                data, inds, x, y, z, ...
                                patch_dim_stack, ...
                                centroids_stack_new, ...
                                rfs_stack, ...
                                do_cn_stack, ...
                                do_un_stack, ...
                                whiten_mean_stack, ...
                                whiten_trans_stack, ...
                                subsample_stack, ...
                                gn_mn_stack, gn_std_stack, ...
                                kmeans_type_stack, ...
                                pooling_offsets_stack, ...
                                pooling_type_stack, ...
                                extract_offsets_stack, ...
                                dd_scaling, ...
                                dd_downsampling, ...
                                ds_mean_noise, ds_std_noise, ...
                                segm_chns, obj_vals, ...
                                0, ...
                                pe_batch_size);

%
% feats_sub = dawmr_compute_features_mex( ...
feats_sub = dawmr_compute_features_debug_mex( ...
                                data_sub, inds, x, y, z_sub, ...
                                patch_dim_stack_sub, ...
                                centroids_stack_sub, ...
                                rfs_stack, ...
                                do_cn_stack, ...
                                do_un_stack, ...
                                whiten_mean_stack, ...
                                whiten_trans_stack, ...
                                subsample_stack, ...
                                gn_mn_stack, gn_std_stack, ...
                                kmeans_type_stack, ...
                                pooling_offsets_stack, ...
                                pooling_type_stack, ...
                                extract_offsets_stack, ...
                                dd_scaling, ...
                                dd_downsampling, ...
                                ds_mean_noise, ds_std_noise, ...
                                segm_chns, obj_vals, ...
                                0, ...
                                pe_batch_size);
             
feats
feats_sub

%%

for n = 1:20
%

data = rand( 5,5,5, 'single');
data_sub = single( resampleRatioCenter( data, r ));

pooling_offsets_stack = {[0 0 0]};
kmeans_type_stack = 3;

%  DATA, CENTROIDS_STACK MUST BE SINGLE!

clear mex;

% feats = dawmr_compute_features_debug_mex( ...
feats = dawmr_compute_features_mex( ...
                                data, inds, x, y, z, ...
                                patch_dim_stack, ...
                                centroids_stack_new, ...
                                rfs_stack, ...
                                do_cn_stack, ...
                                do_un_stack, ...
                                whiten_mean_stack, ...
                                whiten_trans_stack, ...
                                subsample_stack, ...
                                gn_mn_stack, gn_std_stack, ...
                                kmeans_type_stack, ...
                                pooling_offsets_stack, ...
                                pooling_type_stack, ...
                                extract_offsets_stack, ...
                                dd_scaling, ...
                                dd_downsampling, ...
                                ds_mean_noise, ds_std_noise, ...
                                segm_chns, obj_vals, ...
                                0, ...
                                pe_batch_size);


% feats_sub = dawmr_compute_features_debug_mex( ...
feats_sub = dawmr_compute_features_mex( ...
                                data_sub, inds, x, y, z, ...
                                patch_dim_stack, ...
                                centroids_stack_sub, ...
                                rfs_stack, ...
                                do_cn_stack, ...
                                do_un_stack, ...
                                whiten_mean_stack, ...
                                whiten_trans_stack, ...
                                subsample_stack, ...
                                gn_mn_stack, gn_std_stack, ...
                                kmeans_type_stack, ...
                                pooling_offsets_stack, ...
                                pooling_type_stack, ...
                                extract_offsets_stack, ...
                                dd_scaling, ...
                                dd_downsampling, ...
                                ds_mean_noise, ds_std_noise, ...
                                segm_chns, obj_vals, ...
                                0, ...
                                pe_batch_size);
             
feats
feats_sub

end


%% 

% feats = feats./norm(feats)
% feats_sub = feats_sub./norm(feats_sub)


%%

% db1 = load('/groups/saalfeld/home/bogovicj/tmp/dawmr_debug.mat');
% db2 = load('/groups/saalfeld/home/bogovicj/tmp/dawmr_debug2.mat');
% 
% varList = {
%     'patch_dim_stack', ...
%     'centroids_stack', ...
%     'rfs_stack', ...
%     'do_cn_stack', ...
%     'do_un_stack', ...
%     'whiten_mean_stack', ...
%     'whiten_trans_stack', ...
%     'subsample_stack', ...
%     'gn_mn_stack', 'gn_std_stack', ...
%     'kmeans_type_stack', ...
%     'pooling_offsets_stack', ...
%     'pooling_type_stack', ...
%     'extract_offsets_stack', ...
%     'dd_scaling', ...
%     'dd_downsampling', ...
%     'ds_mean_noise', 'ds_std_noise', ...
%     'segm_chns', 'obj_vals', ...
%     'pe_batch_size'};
%                             
% for i = 1:length(varList)
%     varname = varList{i}
%     db1.(varname)
%     db2.(varname)
%     disp(' ************************ ');
% end
